//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRRepairTicketApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string UserID { get; set; }
        public string CommentText { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int RepairTicketID { get; set; }
    
        public virtual RepairTicket RepairTicket { get; set; }
    }
}
